apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
      - name: order-db
        image: postgres:14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "orders"
---
apiVersion: v1
kind: Service
metadata:
  name: order-db # Sets service name
  labels:
    app: order-db # Labels and Selectors
spec:
  selector:
    app: order-db
  ports:
    - protocol: TCP
      port: 5432 # Sets port to run the postgres application
      targetPort: 5432
